/**
 * Workout App Seed Data v1.0
 *
 * spec v4.4 데이터 모델에 맞춰 작성된 초기 시드 데이터.
 *
 * 포함 데이터:
 *   - BodyRegion: 9개 (shoulder_front, wrist, lower_back 등)
 *   - Muscle: 21개 (가슴/등/어깨/팔/하체/코어)
 *   - Exercise: 60개 (헬스장 빅3 + 보조 운동)
 *   - ExerciseVariation: 그립/기구 차이가 의미 있는 종목에만 추가
 *   - ExerciseMuscleMapping: 모든 종목의 주동근/보조근 매핑
 *
 * 사용법 (Dexie 예시):
 *   import { seedData } from './seeds';
 *   await db.transaction('rw', [
 *     db.bodyRegions, db.muscles, db.exercises,
 *     db.exerciseVariations, db.exerciseMuscleMappings
 *   ], async () => {
 *     await db.bodyRegions.bulkAdd(seedData.bodyRegions);
 *     await db.muscles.bulkAdd(seedData.muscles);
 *     await db.exercises.bulkAdd(seedData.exercises);
 *     await db.exerciseVariations.bulkAdd(seedData.exerciseVariations);
 *     await db.exerciseMuscleMappings.bulkAdd(seedData.exerciseMuscleMappings);
 *   });
 */

// =========================================
// 타입 정의 (spec v4.4와 일치)
// =========================================

export type MuscleGroup = 'push' | 'pull' | 'legs' | 'core';
export type ExerciseCategory = 'compound' | 'isolation' | 'mobility' | 'warmup';
export type Equipment =
  | 'barbell'
  | 'dumbbell'
  | 'machine'
  | 'cable'
  | 'bodyweight'
  | 'ez_bar';
export type GripType =
  | 'pronated'
  | 'supinated'
  | 'neutral'
  | 'mixed'
  | 'none';
export type SkillLevel = 'easy' | 'medium' | 'hard';
export type Stability = 'stable' | 'moderate' | 'unstable';
export type MuscleRole = 'primary' | 'secondary' | 'minor' | 'stabilizer';

export interface BodyRegion {
  id: string;
  name_ko: string;
  parent_id: string | null;
}

export interface Muscle {
  id: string;
  name_ko: string;
  group: MuscleGroup;
}

export interface Exercise {
  id: string;
  name: string;
  category: ExerciseCategory;
  default_equipment: Equipment;
  is_custom: boolean;
  target_rep_range: [number, number];
  weight_increment_kg: number;
  default_rest_seconds: number;
  recommendation_bias: number;
  fatigue_factor: number;
  joint_stress_region_ids: string[];
  movement_patterns: string[];
  skill_level: SkillLevel;
  stability: Stability;
  unilateral: boolean;
  alternative_group_id: string | null;
}

export interface ExerciseVariation {
  id: string;
  exercise_id: string;
  name: string;
  grip_type: GripType;
  equipment: Equipment;
  is_default: boolean;
  /**
   * 관절 부담 보정. BodyRegion.id를 키로 사용.
   * 1.0 = 기본 부담, 0.5 = 50% 감소, 0 = 부담 없음.
   */
  joint_stress_modifier: Record<string, number>;
}

export interface ExerciseMuscleMapping {
  exercise_id: string;
  muscle_id: string;
  role: MuscleRole;
  coefficient: number;
}

// =========================================
// BodyRegion
// =========================================

export const bodyRegions: BodyRegion[] = [
  { id: 'shoulder', name_ko: '어깨', parent_id: null },
  { id: 'shoulder_front', name_ko: '전면 어깨', parent_id: 'shoulder' },
  { id: 'shoulder_side', name_ko: '측면 어깨', parent_id: 'shoulder' },
  { id: 'shoulder_rear', name_ko: '후면 어깨', parent_id: 'shoulder' },
  { id: 'elbow', name_ko: '팔꿈치', parent_id: null },
  { id: 'wrist', name_ko: '손목', parent_id: null },
  { id: 'lower_back', name_ko: '허리', parent_id: null },
  { id: 'knee', name_ko: '무릎', parent_id: null },
  { id: 'hip', name_ko: '엉덩이', parent_id: null },
];

// =========================================
// Muscle
// =========================================

export const muscles: Muscle[] = [
  // Push
  { id: 'chest', name_ko: '가슴', group: 'push' },
  { id: 'chest_upper', name_ko: '가슴(상부)', group: 'push' },
  { id: 'chest_lower', name_ko: '가슴(하부)', group: 'push' },
  { id: 'shoulder_front', name_ko: '전면 어깨', group: 'push' },
  { id: 'shoulder_side', name_ko: '측면 어깨', group: 'push' },
  { id: 'triceps', name_ko: '삼두', group: 'push' },

  // Pull
  { id: 'lats', name_ko: '광배', group: 'pull' },
  { id: 'traps_upper', name_ko: '승모(상부)', group: 'pull' },
  { id: 'traps_mid', name_ko: '승모(중하부)', group: 'pull' },
  { id: 'rhomboids', name_ko: '능형근', group: 'pull' },
  { id: 'shoulder_rear', name_ko: '후면 어깨', group: 'pull' },
  { id: 'biceps', name_ko: '이두', group: 'pull' },
  { id: 'forearms', name_ko: '전완', group: 'pull' },
  { id: 'erector_spinae', name_ko: '척추기립근', group: 'pull' },

  // Legs
  { id: 'quads', name_ko: '대퇴사두', group: 'legs' },
  { id: 'hamstrings', name_ko: '햄스트링', group: 'legs' },
  { id: 'glutes', name_ko: '둔근', group: 'legs' },
  { id: 'calves', name_ko: '종아리', group: 'legs' },

  // Core
  { id: 'abs', name_ko: '복근', group: 'core' },
  { id: 'obliques', name_ko: '복사근', group: 'core' },
  { id: 'core', name_ko: '코어 전반', group: 'core' },
];

// =========================================
// Helper: 매핑 생성
// =========================================

function mapping(
  exerciseId: string,
  muscleId: string,
  coefficient: number
): ExerciseMuscleMapping {
  const role: MuscleRole =
    coefficient >= 1.0
      ? 'primary'
      : coefficient >= 0.5
        ? 'secondary'
        : coefficient > 0
          ? 'minor'
          : 'stabilizer';
  return { exercise_id: exerciseId, muscle_id: muscleId, role, coefficient };
}

// =========================================
// Exercise + ExerciseMuscleMapping
// =========================================

export const exercises: Exercise[] = [
  // ===== 가슴 (Chest) =====
  {
    id: 'bench_press_barbell',
    name: '바벨 벤치프레스',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [5, 10],
    weight_increment_kg: 2.5,
    default_rest_seconds: 180,
    recommendation_bias: 1.0,
    fatigue_factor: 1.2,
    joint_stress_region_ids: ['shoulder_front', 'wrist'],
    movement_patterns: ['horizontal_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'chest_horizontal_press',
  },
  {
    id: 'bench_press_dumbbell',
    name: '덤벨 벤치프레스',
    category: 'compound',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 150,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['shoulder_front'],
    movement_patterns: ['horizontal_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'chest_horizontal_press',
  },
  {
    id: 'chest_press_machine',
    name: '머신 체스트프레스',
    category: 'compound',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: [],
    movement_patterns: ['horizontal_press'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'chest_horizontal_press',
  },
  {
    id: 'bench_press_incline_barbell',
    name: '인클라인 바벨 벤치프레스',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [6, 10],
    weight_increment_kg: 2.5,
    default_rest_seconds: 180,
    recommendation_bias: 1.0,
    fatigue_factor: 1.2,
    joint_stress_region_ids: ['shoulder_front', 'wrist'],
    movement_patterns: ['incline_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'chest_incline_press',
  },
  {
    id: 'bench_press_incline_dumbbell',
    name: '인클라인 덤벨 벤치프레스',
    category: 'compound',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 150,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['shoulder_front'],
    movement_patterns: ['incline_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'chest_incline_press',
  },
  {
    id: 'pec_deck',
    name: '펙 덱 플라이',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 5,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: [],
    movement_patterns: ['chest_fly'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'chest_fly',
  },
  {
    id: 'cable_crossover',
    name: '케이블 크로스오버',
    category: 'isolation',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: ['shoulder_front'],
    movement_patterns: ['chest_fly'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'chest_fly',
  },
  {
    id: 'dips_chest',
    name: '딥스 (가슴 강조)',
    category: 'compound',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [6, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 150,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['shoulder_front', 'wrist'],
    movement_patterns: ['vertical_press'],
    skill_level: 'medium',
    stability: 'unstable',
    unilateral: false,
    alternative_group_id: 'chest_dip',
  },
  {
    id: 'push_up',
    name: '푸쉬업',
    category: 'compound',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [10, 20],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: ['wrist'],
    movement_patterns: ['horizontal_press'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'chest_horizontal_press',
  },

  // ===== 등 (Back) =====
  {
    id: 'deadlift_conventional',
    name: '컨벤셔널 데드리프트',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [3, 8],
    weight_increment_kg: 2.5,
    default_rest_seconds: 240,
    recommendation_bias: 1.0,
    fatigue_factor: 1.5,
    joint_stress_region_ids: ['lower_back', 'wrist'],
    movement_patterns: ['hip_hinge'],
    skill_level: 'hard',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'hip_hinge',
  },
  {
    id: 'pull_up',
    name: '풀업 (오버핸드)',
    category: 'compound',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [5, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 150,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['elbow', 'wrist'],
    movement_patterns: ['vertical_pull'],
    skill_level: 'medium',
    stability: 'unstable',
    unilateral: false,
    alternative_group_id: 'back_vertical_pull',
  },
  {
    id: 'chin_up',
    name: '친업 (언더핸드)',
    category: 'compound',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [5, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 150,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['elbow', 'wrist'],
    movement_patterns: ['vertical_pull'],
    skill_level: 'medium',
    stability: 'unstable',
    unilateral: false,
    alternative_group_id: 'back_vertical_pull',
  },
  {
    id: 'assisted_pull_up',
    name: '어시스트 풀업',
    category: 'compound',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [6, 12],
    weight_increment_kg: 2.5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.0,
    joint_stress_region_ids: ['elbow'],
    movement_patterns: ['vertical_pull'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'back_vertical_pull',
  },
  {
    id: 'lat_pulldown_wide',
    name: '랫풀다운 (와이드)',
    category: 'compound',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 2.5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: [],
    movement_patterns: ['vertical_pull'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'back_vertical_pull',
  },
  {
    id: 'lat_pulldown_neutral',
    name: '랫풀다운 (뉴트럴)',
    category: 'compound',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 2.5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: [],
    movement_patterns: ['vertical_pull'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'back_vertical_pull',
  },
  {
    id: 'barbell_row',
    name: '바벨로우 (오버핸드)',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [6, 10],
    weight_increment_kg: 2.5,
    default_rest_seconds: 150,
    recommendation_bias: 1.0,
    fatigue_factor: 1.2,
    joint_stress_region_ids: ['lower_back', 'wrist'],
    movement_patterns: ['horizontal_pull'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'back_horizontal_pull',
  },
  {
    id: 'pendlay_row',
    name: '펜들레이로우',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [5, 8],
    weight_increment_kg: 2.5,
    default_rest_seconds: 180,
    recommendation_bias: 1.0,
    fatigue_factor: 1.2,
    joint_stress_region_ids: ['lower_back', 'wrist'],
    movement_patterns: ['horizontal_pull'],
    skill_level: 'hard',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'back_horizontal_pull',
  },
  {
    id: 'dumbbell_row_one_arm',
    name: '원암 덤벨로우',
    category: 'compound',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 1.0,
    joint_stress_region_ids: [],
    movement_patterns: ['horizontal_pull'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: true,
    alternative_group_id: 'back_horizontal_pull',
  },
  {
    id: 'seated_cable_row',
    name: '시티드 케이블로우',
    category: 'compound',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 2.5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: [],
    movement_patterns: ['horizontal_pull'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'back_horizontal_pull',
  },
  {
    id: 't_bar_row',
    name: 'T바로우',
    category: 'compound',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 2.5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['lower_back'],
    movement_patterns: ['horizontal_pull'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'back_horizontal_pull',
  },
  {
    id: 'machine_row',
    name: '머신로우',
    category: 'compound',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 5,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.85,
    joint_stress_region_ids: [],
    movement_patterns: ['horizontal_pull'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'back_horizontal_pull',
  },
  {
    id: 'face_pull',
    name: '페이스풀',
    category: 'isolation',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [12, 20],
    weight_increment_kg: 2.5,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['rear_delt_pull'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'rear_delt_raise',
  },

  // ===== 어깨 (Shoulders) =====
  {
    id: 'overhead_press_barbell',
    name: '바벨 오버헤드프레스',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [5, 10],
    weight_increment_kg: 1.25,
    default_rest_seconds: 180,
    recommendation_bias: 1.0,
    fatigue_factor: 1.2,
    joint_stress_region_ids: ['shoulder_front', 'wrist', 'lower_back'],
    movement_patterns: ['vertical_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'shoulder_vertical_press',
  },
  {
    id: 'overhead_press_dumbbell',
    name: '덤벨 오버헤드프레스',
    category: 'compound',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['shoulder_front'],
    movement_patterns: ['vertical_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'shoulder_vertical_press',
  },
  {
    id: 'shoulder_press_machine',
    name: '머신 숄더프레스',
    category: 'compound',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: [],
    movement_patterns: ['vertical_press'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'shoulder_vertical_press',
  },
  {
    id: 'arnold_press',
    name: '아놀드프레스',
    category: 'compound',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['shoulder_front'],
    movement_patterns: ['vertical_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'shoulder_vertical_press',
  },
  {
    id: 'lateral_raise_dumbbell',
    name: '덤벨 레터럴 레이즈',
    category: 'isolation',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 1.25,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['side_delt_raise'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'side_delt_raise',
  },
  {
    id: 'lateral_raise_cable',
    name: '케이블 레터럴 레이즈',
    category: 'isolation',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [12, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['side_delt_raise'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: true,
    alternative_group_id: 'side_delt_raise',
  },
  {
    id: 'lateral_raise_machine',
    name: '머신 레터럴 레이즈',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [12, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['side_delt_raise'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'side_delt_raise',
  },
  {
    id: 'rear_delt_fly_dumbbell',
    name: '덤벨 리어 델트 플라이',
    category: 'isolation',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [12, 15],
    weight_increment_kg: 1.25,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: ['lower_back'],
    movement_patterns: ['rear_delt_pull'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'rear_delt_raise',
  },
  {
    id: 'rear_delt_machine',
    name: '머신 리어 델트',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [12, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['rear_delt_pull'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'rear_delt_raise',
  },
  {
    id: 'shrug_barbell',
    name: '바벨 슈러그',
    category: 'isolation',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: ['wrist'],
    movement_patterns: ['shrug'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'shrug',
  },

  // ===== 하체 (Legs) =====
  {
    id: 'squat_back',
    name: '백 스쿼트',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [5, 10],
    weight_increment_kg: 2.5,
    default_rest_seconds: 240,
    recommendation_bias: 1.0,
    fatigue_factor: 1.4,
    joint_stress_region_ids: ['lower_back', 'knee'],
    movement_patterns: ['squat'],
    skill_level: 'hard',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'quad_squat',
  },
  {
    id: 'squat_front',
    name: '프론트 스쿼트',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [5, 10],
    weight_increment_kg: 2.5,
    default_rest_seconds: 240,
    recommendation_bias: 1.0,
    fatigue_factor: 1.4,
    joint_stress_region_ids: ['knee', 'wrist'],
    movement_patterns: ['squat'],
    skill_level: 'hard',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'quad_squat',
  },
  {
    id: 'hack_squat',
    name: '핵 스쿼트',
    category: 'compound',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 5,
    default_rest_seconds: 180,
    recommendation_bias: 1.0,
    fatigue_factor: 1.2,
    joint_stress_region_ids: ['knee'],
    movement_patterns: ['squat'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'quad_squat',
  },
  {
    id: 'leg_press',
    name: '레그프레스',
    category: 'compound',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 5,
    default_rest_seconds: 180,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['knee'],
    movement_patterns: ['squat'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'quad_squat',
  },
  {
    id: 'bulgarian_split_squat',
    name: '불가리안 스플릿 스쿼트',
    category: 'compound',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.2,
    joint_stress_region_ids: ['knee'],
    movement_patterns: ['lunge'],
    skill_level: 'medium',
    stability: 'unstable',
    unilateral: true,
    alternative_group_id: 'quad_unilateral',
  },
  {
    id: 'lunge_dumbbell',
    name: '덤벨 런지',
    category: 'compound',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['knee'],
    movement_patterns: ['lunge'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: true,
    alternative_group_id: 'quad_unilateral',
  },
  {
    id: 'romanian_deadlift',
    name: '루마니안 데드리프트',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [6, 12],
    weight_increment_kg: 2.5,
    default_rest_seconds: 180,
    recommendation_bias: 1.0,
    fatigue_factor: 1.3,
    joint_stress_region_ids: ['lower_back', 'wrist'],
    movement_patterns: ['hip_hinge'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'hip_hinge',
  },
  {
    id: 'leg_curl_lying',
    name: '라잉 레그컬',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: [],
    movement_patterns: ['knee_flexion'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'hamstring_curl',
  },
  {
    id: 'leg_curl_seated',
    name: '시티드 레그컬',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: [],
    movement_patterns: ['knee_flexion'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'hamstring_curl',
  },
  {
    id: 'leg_extension',
    name: '레그 익스텐션',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: ['knee'],
    movement_patterns: ['knee_extension'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'quad_isolation',
  },
  {
    id: 'hip_thrust',
    name: '힙 쓰러스트',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 2.5,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.0,
    joint_stress_region_ids: [],
    movement_patterns: ['hip_extension'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'glute_compound',
  },
  {
    id: 'calf_raise_standing',
    name: '스탠딩 카프 레이즈',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [12, 20],
    weight_increment_kg: 2.5,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['calf_raise'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'calf_raise',
  },
  {
    id: 'calf_raise_seated',
    name: '시티드 카프 레이즈',
    category: 'isolation',
    default_equipment: 'machine',
    is_custom: false,
    target_rep_range: [12, 20],
    weight_increment_kg: 2.5,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['calf_raise'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'calf_raise',
  },

  // ===== 팔 (Arms) =====
  {
    id: 'curl_barbell',
    name: '바벨컬',
    category: 'isolation',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: ['wrist', 'elbow'],
    movement_patterns: ['elbow_flexion'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'biceps_curl',
  },
  {
    id: 'curl_ez_bar',
    name: 'EZ바컬',
    category: 'isolation',
    default_equipment: 'ez_bar',
    is_custom: false,
    target_rep_range: [8, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: ['elbow'],
    movement_patterns: ['elbow_flexion'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'biceps_curl',
  },
  {
    id: 'curl_dumbbell',
    name: '덤벨컬',
    category: 'isolation',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 1.25,
    default_rest_seconds: 75,
    recommendation_bias: 1.0,
    fatigue_factor: 0.85,
    joint_stress_region_ids: [],
    movement_patterns: ['elbow_flexion'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'biceps_curl',
  },
  {
    id: 'curl_hammer',
    name: '덤벨 해머컬',
    category: 'isolation',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 1.25,
    default_rest_seconds: 75,
    recommendation_bias: 1.0,
    fatigue_factor: 0.85,
    joint_stress_region_ids: [],
    movement_patterns: ['elbow_flexion'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'biceps_curl',
  },
  {
    id: 'curl_incline_dumbbell',
    name: '인클라인 덤벨컬',
    category: 'isolation',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: [],
    movement_patterns: ['elbow_flexion'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'biceps_curl',
  },
  {
    id: 'curl_cable',
    name: '케이블컬',
    category: 'isolation',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 75,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: [],
    movement_patterns: ['elbow_flexion'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'biceps_curl',
  },
  {
    id: 'triceps_pushdown',
    name: '트라이셉 푸쉬다운',
    category: 'isolation',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 2.5,
    default_rest_seconds: 75,
    recommendation_bias: 1.0,
    fatigue_factor: 0.8,
    joint_stress_region_ids: ['elbow'],
    movement_patterns: ['elbow_extension'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'triceps_extension',
  },
  {
    id: 'skull_crusher',
    name: '라잉 트라이셉 익스텐션 (스컬크러셔)',
    category: 'isolation',
    default_equipment: 'ez_bar',
    is_custom: false,
    target_rep_range: [10, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: ['elbow'],
    movement_patterns: ['elbow_extension'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'triceps_extension',
  },
  {
    id: 'overhead_triceps_extension',
    name: '오버헤드 트라이셉 익스텐션',
    category: 'isolation',
    default_equipment: 'dumbbell',
    is_custom: false,
    target_rep_range: [10, 15],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: ['elbow', 'shoulder_front'],
    movement_patterns: ['elbow_extension'],
    skill_level: 'easy',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'triceps_extension',
  },
  {
    id: 'close_grip_bench',
    name: '클로즈그립 벤치프레스',
    category: 'compound',
    default_equipment: 'barbell',
    is_custom: false,
    target_rep_range: [6, 10],
    weight_increment_kg: 2.5,
    default_rest_seconds: 150,
    recommendation_bias: 1.0,
    fatigue_factor: 1.1,
    joint_stress_region_ids: ['shoulder_front', 'wrist', 'elbow'],
    movement_patterns: ['horizontal_press'],
    skill_level: 'medium',
    stability: 'moderate',
    unilateral: false,
    alternative_group_id: 'triceps_compound',
  },
  {
    id: 'dips_triceps',
    name: '딥스 (삼두 강조)',
    category: 'compound',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [6, 12],
    weight_increment_kg: 1.25,
    default_rest_seconds: 120,
    recommendation_bias: 1.0,
    fatigue_factor: 1.0,
    joint_stress_region_ids: ['shoulder_front', 'elbow', 'wrist'],
    movement_patterns: ['vertical_press'],
    skill_level: 'medium',
    stability: 'unstable',
    unilateral: false,
    alternative_group_id: 'triceps_compound',
  },

  // ===== 코어 (Core) =====
  {
    id: 'plank',
    name: '플랭크',
    category: 'isolation',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [30, 90],
    weight_increment_kg: 0,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['core_static'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'core_static',
  },
  {
    id: 'hanging_leg_raise',
    name: '행잉 레그 레이즈',
    category: 'isolation',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [8, 15],
    weight_increment_kg: 1.25,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: [],
    movement_patterns: ['hip_flexion'],
    skill_level: 'medium',
    stability: 'unstable',
    unilateral: false,
    alternative_group_id: 'abs_dynamic',
  },
  {
    id: 'cable_crunch',
    name: '케이블 크런치',
    category: 'isolation',
    default_equipment: 'cable',
    is_custom: false,
    target_rep_range: [12, 20],
    weight_increment_kg: 2.5,
    default_rest_seconds: 60,
    recommendation_bias: 1.0,
    fatigue_factor: 0.7,
    joint_stress_region_ids: [],
    movement_patterns: ['spine_flexion'],
    skill_level: 'easy',
    stability: 'stable',
    unilateral: false,
    alternative_group_id: 'abs_dynamic',
  },
  {
    id: 'ab_wheel_rollout',
    name: '앱 휠 롤아웃',
    category: 'isolation',
    default_equipment: 'bodyweight',
    is_custom: false,
    target_rep_range: [8, 15],
    weight_increment_kg: 0,
    default_rest_seconds: 90,
    recommendation_bias: 1.0,
    fatigue_factor: 0.9,
    joint_stress_region_ids: ['lower_back'],
    movement_patterns: ['anti_extension'],
    skill_level: 'medium',
    stability: 'unstable',
    unilateral: false,
    alternative_group_id: 'core_static',
  },
];

// =========================================
// ExerciseMuscleMapping
// 부록 7.2 매핑 초안 기반 + 추가 종목 매핑
// =========================================

export const exerciseMuscleMappings: ExerciseMuscleMapping[] = [
  // ===== 가슴 =====
  mapping('bench_press_barbell', 'chest', 1.0),
  mapping('bench_press_barbell', 'shoulder_front', 0.5),
  mapping('bench_press_barbell', 'triceps', 0.5),

  mapping('bench_press_dumbbell', 'chest', 1.0),
  mapping('bench_press_dumbbell', 'shoulder_front', 0.5),
  mapping('bench_press_dumbbell', 'triceps', 0.5),

  mapping('chest_press_machine', 'chest', 1.0),
  mapping('chest_press_machine', 'shoulder_front', 0.5),
  mapping('chest_press_machine', 'triceps', 0.5),

  mapping('bench_press_incline_barbell', 'chest_upper', 1.0),
  mapping('bench_press_incline_barbell', 'chest', 0.5),
  mapping('bench_press_incline_barbell', 'shoulder_front', 0.5),
  mapping('bench_press_incline_barbell', 'triceps', 0.5),

  mapping('bench_press_incline_dumbbell', 'chest_upper', 1.0),
  mapping('bench_press_incline_dumbbell', 'chest', 0.5),
  mapping('bench_press_incline_dumbbell', 'shoulder_front', 0.5),
  mapping('bench_press_incline_dumbbell', 'triceps', 0.5),

  mapping('pec_deck', 'chest', 1.0),
  mapping('pec_deck', 'shoulder_front', 0.25),

  mapping('cable_crossover', 'chest', 1.0),
  mapping('cable_crossover', 'shoulder_front', 0.25),

  mapping('dips_chest', 'chest_lower', 1.0),
  mapping('dips_chest', 'triceps', 0.5),
  mapping('dips_chest', 'shoulder_front', 0.5),

  mapping('push_up', 'chest', 1.0),
  mapping('push_up', 'shoulder_front', 0.5),
  mapping('push_up', 'triceps', 0.5),
  mapping('push_up', 'core', 0.25),

  // ===== 등 =====
  mapping('deadlift_conventional', 'hamstrings', 1.0),
  mapping('deadlift_conventional', 'glutes', 1.0),
  mapping('deadlift_conventional', 'erector_spinae', 1.0),
  mapping('deadlift_conventional', 'lats', 0.5),
  mapping('deadlift_conventional', 'traps_upper', 0.5),
  mapping('deadlift_conventional', 'forearms', 0.5),
  mapping('deadlift_conventional', 'quads', 0.25),

  mapping('pull_up', 'lats', 1.0),
  mapping('pull_up', 'biceps', 0.5),
  mapping('pull_up', 'rhomboids', 0.5),
  mapping('pull_up', 'shoulder_rear', 0.25),
  mapping('pull_up', 'forearms', 0.5),

  mapping('chin_up', 'lats', 1.0),
  mapping('chin_up', 'biceps', 0.5),
  mapping('chin_up', 'rhomboids', 0.5),
  mapping('chin_up', 'shoulder_rear', 0.25),
  mapping('chin_up', 'forearms', 0.5),

  mapping('assisted_pull_up', 'lats', 1.0),
  mapping('assisted_pull_up', 'biceps', 0.5),
  mapping('assisted_pull_up', 'rhomboids', 0.5),
  mapping('assisted_pull_up', 'shoulder_rear', 0.25),

  mapping('lat_pulldown_wide', 'lats', 1.0),
  mapping('lat_pulldown_wide', 'biceps', 0.5),
  mapping('lat_pulldown_wide', 'rhomboids', 0.5),
  mapping('lat_pulldown_wide', 'shoulder_rear', 0.25),

  mapping('lat_pulldown_neutral', 'lats', 1.0),
  mapping('lat_pulldown_neutral', 'biceps', 0.5),
  mapping('lat_pulldown_neutral', 'rhomboids', 0.5),
  mapping('lat_pulldown_neutral', 'shoulder_rear', 0.25),

  mapping('barbell_row', 'lats', 1.0),
  mapping('barbell_row', 'rhomboids', 1.0),
  mapping('barbell_row', 'traps_mid', 0.5),
  mapping('barbell_row', 'shoulder_rear', 0.5),
  mapping('barbell_row', 'biceps', 0.5),
  mapping('barbell_row', 'erector_spinae', 0.25),

  mapping('pendlay_row', 'lats', 1.0),
  mapping('pendlay_row', 'rhomboids', 1.0),
  mapping('pendlay_row', 'traps_mid', 0.5),
  mapping('pendlay_row', 'shoulder_rear', 0.5),
  mapping('pendlay_row', 'biceps', 0.5),

  mapping('dumbbell_row_one_arm', 'lats', 1.0),
  mapping('dumbbell_row_one_arm', 'rhomboids', 0.5),
  mapping('dumbbell_row_one_arm', 'shoulder_rear', 0.5),
  mapping('dumbbell_row_one_arm', 'biceps', 0.5),

  mapping('seated_cable_row', 'lats', 1.0),
  mapping('seated_cable_row', 'rhomboids', 1.0),
  mapping('seated_cable_row', 'traps_mid', 0.5),
  mapping('seated_cable_row', 'shoulder_rear', 0.5),
  mapping('seated_cable_row', 'biceps', 0.5),

  mapping('t_bar_row', 'lats', 1.0),
  mapping('t_bar_row', 'rhomboids', 1.0),
  mapping('t_bar_row', 'traps_mid', 0.5),
  mapping('t_bar_row', 'shoulder_rear', 0.5),
  mapping('t_bar_row', 'biceps', 0.5),

  mapping('machine_row', 'lats', 1.0),
  mapping('machine_row', 'rhomboids', 1.0),
  mapping('machine_row', 'shoulder_rear', 0.5),
  mapping('machine_row', 'biceps', 0.5),

  mapping('face_pull', 'shoulder_rear', 1.0),
  mapping('face_pull', 'rhomboids', 0.5),
  mapping('face_pull', 'traps_mid', 0.5),

  // ===== 어깨 =====
  mapping('overhead_press_barbell', 'shoulder_front', 1.0),
  mapping('overhead_press_barbell', 'shoulder_side', 0.5),
  mapping('overhead_press_barbell', 'triceps', 0.5),
  mapping('overhead_press_barbell', 'chest_upper', 0.25),
  mapping('overhead_press_barbell', 'core', 0.25),

  mapping('overhead_press_dumbbell', 'shoulder_front', 1.0),
  mapping('overhead_press_dumbbell', 'shoulder_side', 0.5),
  mapping('overhead_press_dumbbell', 'triceps', 0.5),
  mapping('overhead_press_dumbbell', 'chest_upper', 0.25),

  mapping('shoulder_press_machine', 'shoulder_front', 1.0),
  mapping('shoulder_press_machine', 'shoulder_side', 0.5),
  mapping('shoulder_press_machine', 'triceps', 0.5),

  mapping('arnold_press', 'shoulder_front', 1.0),
  mapping('arnold_press', 'shoulder_side', 0.5),
  mapping('arnold_press', 'triceps', 0.5),

  mapping('lateral_raise_dumbbell', 'shoulder_side', 1.0),
  mapping('lateral_raise_dumbbell', 'traps_upper', 0.25),

  mapping('lateral_raise_cable', 'shoulder_side', 1.0),
  mapping('lateral_raise_cable', 'traps_upper', 0.25),

  mapping('lateral_raise_machine', 'shoulder_side', 1.0),
  mapping('lateral_raise_machine', 'traps_upper', 0.25),

  mapping('rear_delt_fly_dumbbell', 'shoulder_rear', 1.0),
  mapping('rear_delt_fly_dumbbell', 'rhomboids', 0.5),
  mapping('rear_delt_fly_dumbbell', 'traps_mid', 0.25),

  mapping('rear_delt_machine', 'shoulder_rear', 1.0),
  mapping('rear_delt_machine', 'rhomboids', 0.5),
  mapping('rear_delt_machine', 'traps_mid', 0.25),

  mapping('shrug_barbell', 'traps_upper', 1.0),
  mapping('shrug_barbell', 'forearms', 0.5),

  // ===== 하체 =====
  mapping('squat_back', 'quads', 1.0),
  mapping('squat_back', 'glutes', 0.5),
  mapping('squat_back', 'hamstrings', 0.25),
  mapping('squat_back', 'erector_spinae', 0.5),
  mapping('squat_back', 'core', 0.5),

  mapping('squat_front', 'quads', 1.0),
  mapping('squat_front', 'glutes', 0.5),
  mapping('squat_front', 'core', 0.5),
  mapping('squat_front', 'erector_spinae', 0.25),

  mapping('hack_squat', 'quads', 1.0),
  mapping('hack_squat', 'glutes', 0.5),
  mapping('hack_squat', 'hamstrings', 0.25),

  mapping('leg_press', 'quads', 1.0),
  mapping('leg_press', 'glutes', 0.5),
  mapping('leg_press', 'hamstrings', 0.25),

  mapping('bulgarian_split_squat', 'quads', 1.0),
  mapping('bulgarian_split_squat', 'glutes', 1.0),
  mapping('bulgarian_split_squat', 'hamstrings', 0.25),
  mapping('bulgarian_split_squat', 'core', 0.25),

  mapping('lunge_dumbbell', 'quads', 1.0),
  mapping('lunge_dumbbell', 'glutes', 0.5),
  mapping('lunge_dumbbell', 'hamstrings', 0.25),

  mapping('romanian_deadlift', 'hamstrings', 1.0),
  mapping('romanian_deadlift', 'glutes', 1.0),
  mapping('romanian_deadlift', 'erector_spinae', 0.5),
  mapping('romanian_deadlift', 'lats', 0.25),
  mapping('romanian_deadlift', 'forearms', 0.5),

  mapping('leg_curl_lying', 'hamstrings', 1.0),
  mapping('leg_curl_lying', 'calves', 0.25),

  mapping('leg_curl_seated', 'hamstrings', 1.0),
  mapping('leg_curl_seated', 'calves', 0.25),

  mapping('leg_extension', 'quads', 1.0),

  mapping('hip_thrust', 'glutes', 1.0),
  mapping('hip_thrust', 'hamstrings', 0.5),
  mapping('hip_thrust', 'quads', 0.25),

  mapping('calf_raise_standing', 'calves', 1.0),

  mapping('calf_raise_seated', 'calves', 1.0),

  // ===== 팔 =====
  mapping('curl_barbell', 'biceps', 1.0),
  mapping('curl_barbell', 'forearms', 0.25),

  mapping('curl_ez_bar', 'biceps', 1.0),
  mapping('curl_ez_bar', 'forearms', 0.25),

  mapping('curl_dumbbell', 'biceps', 1.0),
  mapping('curl_dumbbell', 'forearms', 0.25),

  mapping('curl_hammer', 'biceps', 1.0),
  mapping('curl_hammer', 'forearms', 0.5),

  mapping('curl_incline_dumbbell', 'biceps', 1.0),
  mapping('curl_incline_dumbbell', 'forearms', 0.25),

  mapping('curl_cable', 'biceps', 1.0),
  mapping('curl_cable', 'forearms', 0.25),

  mapping('triceps_pushdown', 'triceps', 1.0),

  mapping('skull_crusher', 'triceps', 1.0),

  mapping('overhead_triceps_extension', 'triceps', 1.0),

  mapping('close_grip_bench', 'triceps', 1.0),
  mapping('close_grip_bench', 'chest', 0.5),
  mapping('close_grip_bench', 'shoulder_front', 0.5),

  mapping('dips_triceps', 'triceps', 1.0),
  mapping('dips_triceps', 'chest_lower', 0.5),
  mapping('dips_triceps', 'shoulder_front', 0.5),

  // ===== 코어 =====
  mapping('plank', 'core', 1.0),
  mapping('plank', 'abs', 0.5),
  mapping('plank', 'obliques', 0.25),

  mapping('hanging_leg_raise', 'abs', 1.0),
  mapping('hanging_leg_raise', 'obliques', 0.5),
  mapping('hanging_leg_raise', 'forearms', 0.25),

  mapping('cable_crunch', 'abs', 1.0),
  mapping('cable_crunch', 'obliques', 0.25),

  mapping('ab_wheel_rollout', 'abs', 1.0),
  mapping('ab_wheel_rollout', 'core', 0.5),
  mapping('ab_wheel_rollout', 'lats', 0.25),
];

// =========================================
// ExerciseVariation
// 같은 종목의 그립/핸들 변형 (다른 종목은 별도 Exercise로 분리되어 있음)
// 부상 사용자에게 의미 있는 변형 중심으로 작성
// =========================================

export const exerciseVariations: ExerciseVariation[] = [
  // 바벨 벤치프레스: 그립 너비 변형
  {
    id: 'bench_press_barbell_default',
    exercise_id: 'bench_press_barbell',
    name: '일반 그립',
    grip_type: 'pronated',
    equipment: 'barbell',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'bench_press_barbell_close',
    exercise_id: 'bench_press_barbell',
    name: '내로우 그립 (어깨 너비)',
    grip_type: 'pronated',
    equipment: 'barbell',
    is_default: false,
    joint_stress_modifier: { shoulder_front: 0.7, wrist: 1.0 },
  },

  // 덤벨 벤치프레스: 그립 방향
  {
    id: 'bench_press_dumbbell_default',
    exercise_id: 'bench_press_dumbbell',
    name: '프로네이트 그립 (기본)',
    grip_type: 'pronated',
    equipment: 'dumbbell',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'bench_press_dumbbell_neutral',
    exercise_id: 'bench_press_dumbbell',
    name: '뉴트럴 그립 (헥스 프레스)',
    grip_type: 'neutral',
    equipment: 'dumbbell',
    is_default: false,
    joint_stress_modifier: { shoulder_front: 0.6, wrist: 0.5 },
  },

  // 오버헤드프레스: 시팅 여부
  {
    id: 'overhead_press_barbell_standing',
    exercise_id: 'overhead_press_barbell',
    name: '스탠딩 (기본)',
    grip_type: 'pronated',
    equipment: 'barbell',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'overhead_press_barbell_seated',
    exercise_id: 'overhead_press_barbell',
    name: '시티드',
    grip_type: 'pronated',
    equipment: 'barbell',
    is_default: false,
    joint_stress_modifier: { lower_back: 0.5 },
  },

  // 덤벨 OHP: 그립 방향
  {
    id: 'overhead_press_dumbbell_default',
    exercise_id: 'overhead_press_dumbbell',
    name: '프로네이트 그립 (기본)',
    grip_type: 'pronated',
    equipment: 'dumbbell',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'overhead_press_dumbbell_neutral',
    exercise_id: 'overhead_press_dumbbell',
    name: '뉴트럴 그립',
    grip_type: 'neutral',
    equipment: 'dumbbell',
    is_default: false,
    joint_stress_modifier: { shoulder_front: 0.6 },
  },

  // 풀업: 그립 너비
  {
    id: 'pull_up_default',
    exercise_id: 'pull_up',
    name: '일반 그립 (어깨 너비)',
    grip_type: 'pronated',
    equipment: 'bodyweight',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'pull_up_wide',
    exercise_id: 'pull_up',
    name: '와이드 그립',
    grip_type: 'pronated',
    equipment: 'bodyweight',
    is_default: false,
    joint_stress_modifier: { elbow: 1.2, wrist: 1.0 },
  },
  {
    id: 'pull_up_neutral',
    exercise_id: 'pull_up',
    name: '뉴트럴 그립 (패러렐)',
    grip_type: 'neutral',
    equipment: 'bodyweight',
    is_default: false,
    joint_stress_modifier: { elbow: 0.6, wrist: 0.5 },
  },

  // 바벨컬: 그립 너비
  {
    id: 'curl_barbell_default',
    exercise_id: 'curl_barbell',
    name: '일반 그립',
    grip_type: 'supinated',
    equipment: 'barbell',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'curl_barbell_wide',
    exercise_id: 'curl_barbell',
    name: '와이드 그립',
    grip_type: 'supinated',
    equipment: 'barbell',
    is_default: false,
    joint_stress_modifier: { wrist: 1.2 },
  },

  // 트라이셉 푸쉬다운: 핸들 종류
  {
    id: 'triceps_pushdown_rope',
    exercise_id: 'triceps_pushdown',
    name: '로프',
    grip_type: 'neutral',
    equipment: 'cable',
    is_default: true,
    joint_stress_modifier: { elbow: 0.7 },
  },
  {
    id: 'triceps_pushdown_v_bar',
    exercise_id: 'triceps_pushdown',
    name: 'V바',
    grip_type: 'pronated',
    equipment: 'cable',
    is_default: false,
    joint_stress_modifier: {},
  },
  {
    id: 'triceps_pushdown_straight_bar',
    exercise_id: 'triceps_pushdown',
    name: '스트레이트 바',
    grip_type: 'pronated',
    equipment: 'cable',
    is_default: false,
    joint_stress_modifier: { wrist: 1.1 },
  },

  // 시티드 케이블로우: 핸들 종류
  {
    id: 'seated_cable_row_v_handle',
    exercise_id: 'seated_cable_row',
    name: 'V 핸들 (뉴트럴)',
    grip_type: 'neutral',
    equipment: 'cable',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'seated_cable_row_wide_bar',
    exercise_id: 'seated_cable_row',
    name: '와이드 바 (프로네이트)',
    grip_type: 'pronated',
    equipment: 'cable',
    is_default: false,
    joint_stress_modifier: { wrist: 1.1 },
  },

  // 랫풀다운(뉴트럴): 핸들 종류
  {
    id: 'lat_pulldown_neutral_v',
    exercise_id: 'lat_pulldown_neutral',
    name: 'V 핸들',
    grip_type: 'neutral',
    equipment: 'cable',
    is_default: true,
    joint_stress_modifier: {},
  },
  {
    id: 'lat_pulldown_neutral_parallel',
    exercise_id: 'lat_pulldown_neutral',
    name: '패러렐 바',
    grip_type: 'neutral',
    equipment: 'cable',
    is_default: false,
    joint_stress_modifier: {},
  },
];

// =========================================
// 통합 export
// =========================================

export const seedData = {
  bodyRegions,
  muscles,
  exercises,
  exerciseMuscleMappings,
  exerciseVariations,
};

export default seedData;
